In [1]:
import math

In [2]:
import numpy as np

In [40]:
import array as arr

In [4]:
l=[1,2,'shu','bhu',45.5]
type(l)

list

In [7]:
np.array(l)

array(['1', '2', 'shu', 'bhu', '45.5'], dtype='<U32')

In [11]:
type(np.array(l))    #numpy.n dimentional array

numpy.ndarray

In [18]:
np.array([[1,2],[3,4],[5,6],['s','r']])

array([['1', '2'],
       ['3', '4'],
       ['5', '6'],
       ['s', 'r']], dtype='<U11')

In [19]:
np.array([1,2,3])

array([1, 2, 3])

In [20]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [21]:
type(np.array([1,2,3],ndmin=3))

numpy.ndarray

In [26]:
np.array([1,2,3], dtype= str)

array(['1', '2', '3'], dtype='<U1')

In [27]:
np.array([1,2,3], dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [51]:
a=np.array([(1,2),(3,4)])

In [52]:
a[1][1]

4

In [54]:
a[0][1]

2

In [55]:
l=[3,4,5,6,7]

In [56]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [57]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [58]:
np.array(l)

array([3, 4, 5, 6, 7])

In [61]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
arr[1][2]

6

In [63]:
arr[1][2]=40

In [64]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 40],
       [ 7,  8,  9]])

In [66]:
arr[0:10]

array([[ 1,  2,  3],
       [ 4,  5, 40],
       [ 7,  8,  9]])

In [67]:
arr[-1]

array([7, 8, 9])

In [68]:
arr[2]

array([7, 8, 9])

In [69]:
arr[0]

array([1, 2, 3])

In [70]:
for i in arr:
    print(i)

[1 2 3]
[ 4  5 40]
[7 8 9]


In [2]:
import math

In [3]:
import numpy as n

In [4]:
import array as ar

In [4]:
n.array([12,34,56,'shubh'])

array(['12', '34', '56', 'shubh'], dtype='<U11')

In [6]:
type(n.array([12,34,56,'shubh']))

numpy.ndarray

In [9]:
n.array([12,34,56,],dtype='complex')

array([12.+0.j, 34.+0.j, 56.+0.j])

In [4]:
n.fromfunction(lambda i,j: i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [5]:
n.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [6]:
n.fromfunction(lambda i,j : i/j, (3,3))

C:\Users\SHUBHANGINI\AppData\Local\Temp\ipykernel_9780\1645126524.py:1: RuntimeWarning: divide by zero encountered in true_divide
  n.fromfunction(lambda i,j : i/j, (3,3))
C:\Users\SHUBHANGINI\AppData\Local\Temp\ipykernel_9780\1645126524.py:1: RuntimeWarning: invalid value encountered in true_divide
  n.fromfunction(lambda i,j : i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [9]:
n.fromstring('1,2,3,4',sep=',',dtype=float)

array([1., 2., 3., 4.])

In [11]:
n.arange(6)

array([0, 1, 2, 3, 4, 5])

In [12]:
n.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [15]:
n.arange(6,10,2)    #slicing

array([6, 8])

In [17]:
n.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [19]:
n.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [20]:
n.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
n.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
n.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
n.ones((2,3,2))+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [26]:
n.eye(3)    #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

n.empty(6

In [95]:
n.empty(8)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 4.67289956e-307,
       2.67017691e-306, 1.42413555e-306, 1.78019082e-306, 1.37959740e-306])

In [30]:
n.linspace(2,4,4,axis=0)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [31]:
n.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [35]:
d=n.linspace(4,5,40)

In [36]:
d

array([4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
       4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
       4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
       4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949,
       4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
       4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
       4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
       4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ])

In [37]:
d.shape

(40,)

In [41]:
d.reshape(10,4)

array([[4.        , 4.02564103, 4.05128205, 4.07692308],
       [4.1025641 , 4.12820513, 4.15384615, 4.17948718],
       [4.20512821, 4.23076923, 4.25641026, 4.28205128],
       [4.30769231, 4.33333333, 4.35897436, 4.38461538],
       [4.41025641, 4.43589744, 4.46153846, 4.48717949],
       [4.51282051, 4.53846154, 4.56410256, 4.58974359],
       [4.61538462, 4.64102564, 4.66666667, 4.69230769],
       [4.71794872, 4.74358974, 4.76923077, 4.79487179],
       [4.82051282, 4.84615385, 4.87179487, 4.8974359 ],
       [4.92307692, 4.94871795, 4.97435897, 5.        ]])

In [43]:
d.reshape(20,2)

array([[4.        , 4.02564103],
       [4.05128205, 4.07692308],
       [4.1025641 , 4.12820513],
       [4.15384615, 4.17948718],
       [4.20512821, 4.23076923],
       [4.25641026, 4.28205128],
       [4.30769231, 4.33333333],
       [4.35897436, 4.38461538],
       [4.41025641, 4.43589744],
       [4.46153846, 4.48717949],
       [4.51282051, 4.53846154],
       [4.56410256, 4.58974359],
       [4.61538462, 4.64102564],
       [4.66666667, 4.69230769],
       [4.71794872, 4.74358974],
       [4.76923077, 4.79487179],
       [4.82051282, 4.84615385],
       [4.87179487, 4.8974359 ],
       [4.92307692, 4.94871795],
       [4.97435897, 5.        ]])

In [47]:
n.random.rand(3)    #random data creating  in b/w 0-1

array([0.27127521, 0.27409038, 0.73839852])

In [48]:
n.random.rand(5,4)

array([[0.484515  , 0.19841475, 0.77827654, 0.57858608],
       [0.56090392, 0.46255462, 0.04877868, 0.95083993],
       [0.03167564, 0.16662092, 0.56864893, 0.00958299],
       [0.65051238, 0.17751301, 0.11114496, 0.02926803],
       [0.38740093, 0.82144527, 0.55141184, 0.54365169]])

In [49]:
n.random.rand(2,2,3)

array([[[0.76991276, 0.59269287, 0.26368926],
        [0.23246133, 0.91448057, 0.13708659]],

       [[0.51306191, 0.8539861 , 0.19538805],
        [0.39377748, 0.98784583, 0.66860428]]])

In [51]:
n.random.randint(4)

3

In [53]:
n.random.randint((5,6),40)

array([14, 32])

In [55]:
n.random.randn(4,4)

array([[-0.65792354, -0.74897273, -0.48230689, -0.10626408],
       [ 0.42798883,  0.16882385, -0.31110422, -0.21951358],
       [-0.50597428, -0.13449044, -2.02861212, -1.04904749],
       [-1.18849297,  1.36270757, -0.87737217,  0.178491  ]])

In [118]:
ar=n.random.randint(3,9,(3,3))

In [119]:
ar

array([[7, 3, 4],
       [7, 8, 8],
       [4, 5, 6]])

In [120]:
ar.reshape(1,1,9)

array([[[7, 3, 4, 7, 8, 8, 4, 5, 6]]])

In [121]:
ar.reshape(3,3,1)

array([[[7],
        [3],
        [4]],

       [[7],
        [8],
        [8]],

       [[4],
        [5],
        [6]]])

In [122]:
ar.reshape(3,-1)

array([[7, 3, 4],
       [7, 8, 8],
       [4, 5, 6]])

In [123]:
ar.reshape(3,-9988)

array([[7, 3, 4],
       [7, 8, 8],
       [4, 5, 6]])

In [124]:
ar.max()

8

In [125]:
ar.min()

3

In [126]:
ar=n.random.randint(4,100,(5,5))

In [127]:
ar

array([[78,  4, 80, 17, 86],
       [93, 39, 66, 39, 37],
       [34, 67, 22, 90, 54],
       [84, 88, 10, 77, 49],
       [34, 36, 31, 63, 93]])

In [128]:
ar[3:,3:]   #will eliminate matrix in 3*3 and give rest matrix entries

array([[77, 49],
       [63, 93]])

In [129]:
ar[:,[1,3]]

array([[ 4, 17],
       [39, 39],
       [67, 90],
       [88, 77],
       [36, 63]])

In [130]:
ar[ar>50]

array([78, 80, 86, 93, 66, 67, 90, 54, 84, 88, 77, 63, 93])

In [131]:
ar>50

array([[ True, False,  True, False,  True],
       [ True, False,  True, False, False],
       [False,  True, False,  True,  True],
       [ True,  True, False,  True, False],
       [False, False, False,  True,  True]])

In [132]:
ar*ar

array([[6084,   16, 6400,  289, 7396],
       [8649, 1521, 4356, 1521, 1369],
       [1156, 4489,  484, 8100, 2916],
       [7056, 7744,  100, 5929, 2401],
       [1156, 1296,  961, 3969, 8649]])

In [133]:
ar1=n.random.randint(2,5,(2,2))

In [134]:
ar2=n.random.randint(2,5,(2,2))

In [135]:
ar1*ar2

array([[4, 6],
       [8, 6]])

In [136]:
ar1@ar2

array([[10, 10],
       [14, 14]])

In [137]:
ar1

array([[2, 3],
       [4, 3]])

In [138]:
ar2

array([[2, 2],
       [2, 2]])

In [139]:
ar**2

array([[6084,   16, 6400,  289, 7396],
       [8649, 1521, 4356, 1521, 1369],
       [1156, 4489,  484, 8100, 2916],
       [7056, 7744,  100, 5929, 2401],
       [1156, 1296,  961, 3969, 8649]], dtype=int32)

In [140]:
ar/0

C:\Users\SHUBHANGINI\AppData\Local\Temp\ipykernel_2564\1327486518.py:1: RuntimeWarning: divide by zero encountered in true_divide
  ar/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [141]:
n.log(ar)  #log values for ar matrix

array([[4.35670883, 1.38629436, 4.38202663, 2.83321334, 4.4543473 ],
       [4.53259949, 3.66356165, 4.18965474, 3.66356165, 3.61091791],
       [3.52636052, 4.20469262, 3.09104245, 4.49980967, 3.98898405],
       [4.4308168 , 4.47733681, 2.30258509, 4.34380542, 3.8918203 ],
       [3.52636052, 3.58351894, 3.4339872 , 4.14313473, 4.53259949]])

In [142]:
n.random.seed(1)
n.random.rand(2,4)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01]])

In [6]:
n.random.seed(11)
n.random.rand(3,5)

array([[0.18026969, 0.01947524, 0.46321853, 0.72493393, 0.4202036 ],
       [0.4854271 , 0.01278081, 0.48737161, 0.94180665, 0.85079509],
       [0.72996447, 0.10873607, 0.89390417, 0.85715425, 0.16508662]])

In [7]:
n.random.seed(11)
n.random.rand(3,5)

array([[0.18026969, 0.01947524, 0.46321853, 0.72493393, 0.4202036 ],
       [0.4854271 , 0.01278081, 0.48737161, 0.94180665, 0.85079509],
       [0.72996447, 0.10873607, 0.89390417, 0.85715425, 0.16508662]])

In [8]:
n.random.seed(3)
n.random.rand(2,2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761]])

In [9]:
n.random.seed(3)
n.random.rand(2,2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761]])

In [10]:
n.random.rand(2,2)

array([[0.89294695, 0.89629309],
       [0.12558531, 0.20724288]])

In [15]:
n.random.seed(12)
n.random.rand(2,2)

array([[0.15416284, 0.7400497 ],
       [0.26331502, 0.53373939]])

In [18]:
ar

<module 'array' (built-in)>

In [19]:
import math
import numpy as np
import array as arr

In [20]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [21]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],['s','p']])

In [22]:
arr

array([['1', '2'],
       ['3', '4'],
       ['5', '6'],
       ['7', '8'],
       ['s', 'p']], dtype='<U11')

In [28]:
arr[4][0]

's'

In [29]:
type(arr)

numpy.ndarray

In [32]:
np.array([1,2,3,4],dtype='str')

array(['1', '2', '3', '4'], dtype='<U1')

In [34]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [41]:
np.fromfunction(lambda i,j:i*j,(6,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 0.,  3.,  6.,  9., 12., 15.],
       [ 0.,  4.,  8., 12., 16., 20.],
       [ 0.,  5., 10., 15., 20., 25.]])

In [42]:
np.fromfunction(lambda i,j:i/j,(5,5))

C:\Users\SHUBHANGINI\AppData\Local\Temp\ipykernel_2564\3599185761.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(5,5))
C:\Users\SHUBHANGINI\AppData\Local\Temp\ipykernel_2564\3599185761.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(5,5))


array([[       nan, 0.        , 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 2.        , 1.        , 0.66666667, 0.5       ],
       [       inf, 3.        , 1.5       , 1.        , 0.75      ],
       [       inf, 4.        , 2.        , 1.33333333, 1.        ]])

In [45]:
np.fromstring('1,2,3,4',sep=',',dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [47]:
n.arange(4)

array([0, 1, 2, 3])

In [50]:
n.arange(3.4)

array([0., 1., 2., 3.])

In [52]:
n.arange(3,9,2)

array([3, 5, 7])

In [54]:
n.linspace(3,2)

array([3.        , 2.97959184, 2.95918367, 2.93877551, 2.91836735,
       2.89795918, 2.87755102, 2.85714286, 2.83673469, 2.81632653,
       2.79591837, 2.7755102 , 2.75510204, 2.73469388, 2.71428571,
       2.69387755, 2.67346939, 2.65306122, 2.63265306, 2.6122449 ,
       2.59183673, 2.57142857, 2.55102041, 2.53061224, 2.51020408,
       2.48979592, 2.46938776, 2.44897959, 2.42857143, 2.40816327,
       2.3877551 , 2.36734694, 2.34693878, 2.32653061, 2.30612245,
       2.28571429, 2.26530612, 2.24489796, 2.2244898 , 2.20408163,
       2.18367347, 2.16326531, 2.14285714, 2.12244898, 2.10204082,
       2.08163265, 2.06122449, 2.04081633, 2.02040816, 2.        ])

In [58]:
n.linspace(3,5,6)

array([3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [60]:
n.zeros(4)+5

array([5., 5., 5., 5.])

In [63]:
n.ones(5)

array([1., 1., 1., 1., 1.])

In [66]:
n.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [73]:
n.ones((2,5,3))+4

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [74]:
n.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
n.empty(8)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 4.67289956e-307,
       2.67017691e-306, 1.42413555e-306, 1.78019082e-306, 1.37959740e-306])

In [102]:
n.logspace([2,5],4)

array([[   100.        , 100000.        ],
       [   109.8541142 ,  95409.547635  ],
       [   120.67926406,  91029.81779915],
       [   132.57113656,  86851.13737514],
       [   145.63484775,  82864.27728547],
       [   159.98587196,  79060.43210908],
       [   175.75106249,  75431.20063355],
       [   193.06977289,  71968.56730012],
       [   212.09508879,  68664.88450043],
       [   232.99518105,  65512.85568596],
       [   255.95479227,  62505.51925274],
       [   281.1768698 ,  59636.23316595],
       [   308.88435965,  56898.66029018],
       [   339.32217719,  54286.75439324],
       [   372.75937203,  51794.74679231],
       [   409.49150624,  49417.13361324],
       [   449.8432669 ,  47148.66363457],
       [   494.17133613,  44984.32668969],
       [   542.86754393,  42919.34260129],
       [   596.36233166,  40949.1506238 ],
       [   655.12855686,  39069.39937055],
       [   719.685673  ,  37275.93720315],
       [   790.60432109,  35564.80306223],
       [   

In [105]:
k=np.linspace(2,3,30)

In [106]:
k

array([2.        , 2.03448276, 2.06896552, 2.10344828, 2.13793103,
       2.17241379, 2.20689655, 2.24137931, 2.27586207, 2.31034483,
       2.34482759, 2.37931034, 2.4137931 , 2.44827586, 2.48275862,
       2.51724138, 2.55172414, 2.5862069 , 2.62068966, 2.65517241,
       2.68965517, 2.72413793, 2.75862069, 2.79310345, 2.82758621,
       2.86206897, 2.89655172, 2.93103448, 2.96551724, 3.        ])

In [108]:
k.shape

(30,)

In [111]:
k.reshape(10,3)

array([[2.        , 2.03448276, 2.06896552],
       [2.10344828, 2.13793103, 2.17241379],
       [2.20689655, 2.24137931, 2.27586207],
       [2.31034483, 2.34482759, 2.37931034],
       [2.4137931 , 2.44827586, 2.48275862],
       [2.51724138, 2.55172414, 2.5862069 ],
       [2.62068966, 2.65517241, 2.68965517],
       [2.72413793, 2.75862069, 2.79310345],
       [2.82758621, 2.86206897, 2.89655172],
       [2.93103448, 2.96551724, 3.        ]])